"""empty message

Revision ID: 328a1023269b
Revises: ba3312d1fa1c
Create Date: 2024-01-11 21:26:24.893066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '328a1023269b'
down_revision = 'ba3312d1fa1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_businesses_profile_id_profiles', type_='foreignkey')
        batch_op.drop_column('profile_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_businesses_profile_id_profiles', 'profiles', ['profile_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')

    # ### end Alembic commands ###
